name: Build, Test, Deploy

on:
 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
          
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.2' # The Go version to download (if necessary) and use.
      - run: go version
      - run: go build main.go
  
  test:
    name: Test
    runs-on: "ubuntu-latest"
    needs: build
          
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.2' # The Go version to download (if necessary) and use.
      - run: go test -run ''

  deploy:
    if: github.event.push
    name: Deploy the app to cloud.gov
    runs-on: "ubuntu-latest"
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: cloud-gov/cg-cli-tools@main
        with: 
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: sandbox-epa
          cf_space: heese.michael

